version: "3.8"

services:
  db:
    image: postgres:15
    container_name: odoo_db
    env_file:
      - ./env/db.env
    ports:
      - "5433:5432"
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:15
    container_name: odoo_15
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
      - ./etc/odoo.conf:/etc/odoo.conf
    env_file:
      - ./env/odoo.env
    environment:
      - ODOO_MODULES=${ODOO_MODULES:-all}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: ["sh", "-c", "odoo -u $ODOO_MODULES"]
    restart: unless-stopped

  dev-watcher:
    image: odoo-watcher
    build:
      context: ./dev-watcher
      dockerfile: Dockerfile
    container_name: odoo_watcher
    volumes:
      - ./custom_addons:/mnt/extra-addons:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./env/odoo.env
    depends_on:
      - odoo
    restart: unless-stopped

volumes:
  odoo_db_data:
  odoo_data:
